In [2]:
import requests
import pandas as pd

# agafem el dataframe llibres.csv 
llibres = pd.read_csv('llibres.csv', sep=',')
llibres.head()

,isbn,book_id,similar_books,average_rating,description,authors,isbn13,num_pages,publication_year,title,language_code
0,0800759494,89375,"['299795', '8100288', '7570892', '53817', '121...",3.91,As he is driving home from a minister's confer...,"['39054', '11099']",9780800759490,NaN,NaN,90 Minutes in Heaven: A True Story of Death an...,NaN
1,0842379428,89376,"['45366', '246849', '11096385', '19102466', '7...",4.26,What is Heaven really going to be like? What w...,['4862'],9780842379427,533.0,NaN,Heaven,eng
2,1503945650,25317381,"['23992482', '21995039', '16065476', '23006790...",3.69,An Amazon Best Book of the Year\nA Goodreads B...,['3111153'],9781503945654,340.0,2015.0,Smoke,eng
3,NaN,26864719,"['25653691', '18106800', '29566096', '26547917...",3.65,He wanted a baby. I needed a man.\nFaith\nThe ...,['14425920'],NaN,NaN,NaN,Bad Boy Daddy,en-GB
4,NaN,12077902,"['2108205', '331256', '553907', '1451628', '14...",3.98,A classic work of science fiction by renowned ...,"['10991', '487600', '4302324']",NaN,8.0,2011.0,Solaris: The Definitive Edition,eng

In [ ]:
#